# Generated by Django 3.1.6 on 2021-02-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_news.png', upload_to='news_pics'),
        ),
    ]
