# Generated by Django 3.1.6 on 2021-02-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20210202_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default_news.png', upload_to='news_pics'),
        ),
    ]
