# Generated by Django 3.1.6 on 2021-02-05 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
