# Generated by Django 3.1.6 on 2021-02-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20210205_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-date_posted',)},
        ),
    ]
